before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang-$LLVM_VERSION
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
  - export

node_js:
  - "node"
branches:
  only:
  - travis_test

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "eb269827b609"
  - COMMIT_AUTHOR_EMAIL: "Deamon87@travis.com"
  - LLVM_VERSION=3.9.0
  - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
  - LLVM_ROOT=$HOME/clang-$LLVM_VERSION/bin
  - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
  - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
  - CXXFLAGS=-lc++
  - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH