addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - llvm-toolchain-precise-3.8
    packages:
    # install toolchains
    - clang-3.8

node_js:
  - "node"
branches:
  only:
  - travis_test

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "eb269827b609"
  - COMMIT_AUTHOR_EMAIL: "Deamon87@travis.com"
