language: cpp

node_js:
  - "node"
branches:
  only:
  - travis_test

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "eb269827b609"
  - COMMIT_AUTHOR_EMAIL: "Deamon87@travis.com"


matrix:
  include:
   - os: linux
     env:
       - LLVM=/usr/local/clang-3.8/bin
     compiler: clang
     addons:
       apt:
         sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
         packages: ['clang-3.8']
     env: COMPILER=clang++-3.8